routes/web.php
<?php

use App\Http\Controllers\PostController;
use App\Http\Controllers\SiteController;
use App\Http\Livewire\Admin\Dashboard;
use App\Http\Livewire\Admin\PostIndex;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[SiteController::class,'index'])->name('home');
Route::get('/testes',function(){
    echo 'Teste is running';
});
Route::get('portfolio/{post:slug}',[SiteController::class,'project'])->name('project');

Route::prefix('admin')->middleware(['auth'])->name('admin.')->group(function () {
    Route::get('/',Dashboard::class)->name('dashboard');
    Route::get('/posts',PostIndex::class)->name('posts');
});

require __DIR__.'/auth.php';

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class Post extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'description',
        'cover',
        'type',
    ];

    public function setTitleAttribute($value)
    {
        $this->attributes['title'] = $value;
        $this->attributes['slug'] = Str::slug($value);
    }

    public function photoCover()
    {
        return $this->cover
        ? Storage::disk()->url('post/covers/'.$this->cover)
        : '';
    }

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/SiteController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;

class SiteController extends Controller
{
    public function index()
    {
        return view('home',[
            'projects' => Post::where('type', 'project')->get()
        ]);
    }

    public function project(Post $post)
    {
        return view('project',['post' => $post]);
    }
}

app/Http/Livewire/Admin/Dashboard.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;

class Dashboard extends Component
{
    public function render()
    {
        return view('livewire.admin.dashboard')->layout('layouts.app',['header' => 'Dashboard']);
    }
}

app/Http/Livewire/Admin/PostCrud.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Post;
use Illuminate\Support\Facades\Storage;
use Livewire\Component;
use Livewire\WithFileUploads;

class PostCrud extends Component
{

    use WithFileUploads;

    public $current_id, $mode;
    public $title, $description, $type, $slug, $order, $cover, $coverInput;

    protected $listeners = ['destroy','edit'];

    protected $rules = [
        'title' => 'required|min:5',
        'type' => 'required',
    ];

    public function mount()
    {
        $this->description = '';
    }

    public function resetInputs()
    {
        $this->reset();
        $this->description = '';
        $this->resetErrorBag();
        $this->dispatchBrowserEvent('reset');
    }

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function show($id)
    {

    }

    public function edit($id)
    {
        $this->mode = 'edit';

        $this->current_id = $id;

        $post = Post::findOrFail($id);

        $this->fill($post);

        $this->dispatchBrowserEvent('open-modal',['name' => 'new']);
    }

    public function store()
    {

        $this->validate();

        if($this->current_id && $this->mode === 'edit')
        {
            $post = Post::findOrFail($this->current_id);
        }
        else
        {
            $post = new Post();
            $post->order = Post::max('order') + 1;
        }

        $post->title = $this->title;
        $post->description = $this->description;
        $post->type = $this->type;

        if($this->coverInput)
        {
            $this->validate([
                'coverInput' => 'nullable|image|max:1024',
            ]);

            if($post->cover){
                Storage::delete('post/covers/'.$post->cover);
            }
            if($path = $this->coverInput->store('post/covers')){
                $path = explode('post/covers/',$path);
                $post->cover = $path[1];
            }
        }
        $post->save();

        $this->dispatchBrowserEvent('notify',['success' => 'Post cadastrado com sucesso!']);
        $this->dispatchBrowserEvent('close-modal',['time' => 0]);
        $this->resetInputs();
        $this->emitTo('admin.post-index','$refresh');
    }

    public function destroy($id)
    {
        if($id)
        {
            $post = Post::find($id);

            if($post->cover){
                Storage::delete('post/covers/'.$post->cover);
            }

            if($post->delete())
            {
                $this->dispatchBrowserEvent('notify',['success' => 'Post excluído com Sucesso!!']);
                $this->emitTo('admin.post-index','$refresh');
            }
        }
    }

    public function render()
    {
        return view('livewire.admin.post-crud');
    }
}

app/Http/Livewire/Admin/PostIndex.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Post;
use Livewire\Component;
use Livewire\WithPagination;

class PostIndex extends Component
{
    use WithPagination;

    public $search;

    protected $listeners = ['$refresh'];

    public function mount()
    {
        $this->dispatchBrowserEvent('notify',['success' => 'Post cadastrado com sucesso!']);
    }

    public function render()
    {
        return view('livewire.admin.post-index',[
            'posts' => Post::where('title','like','%'.$this->search.'%')->orderBy('order','DESC')->paginate(10)
        ])->layout('layouts.app',['header'=>'Posts']);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/admin/post-form.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Post') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/home.blade.php
<x-guest-layout>
    <section class="relative w-full flex flex-col items-center justify-center min-h-screen">
        <figure class="z-10 rounded-full border-[20px] border-opacity-60 border-gray-600 w-64 h-64 shadow-xl">
            <img src="{{asset('storage/images/rondi.jpeg')}}" alt=""
                class="w-full h-full rounded-full border-[10px] border-green-800 shadow-lg">
        </figure>
        <div class="rounded-lg pb-10 -mt-1 px-14">
            <h1 class="text-white font-light text-[65px] text-center">
                RONDINEILER
            </h1>
            <div class="-mt-3 ">
                <p class="text-white text-[30px] text-center font-light">Web Developer</p>
            </div>
        </div>
        <article class="text-white text-center mt-4 text-lg mx-auto max-w-[700px]">
            <p>
                Olá! Meu nome é Rondineiler de Paula, sou desenvolvedor fullstack e atuo com foco em
                soluções para a
                web, sou graduado em Sistemas de Informação e atuo na área a 3 anos desenvolvendo sites, landing
                pages e sistemas personalizados com as melhores práticas.
            </p>
        </article>
        <svg xmlns="http://www.w3.org/2000/svg" class="absolute bottom-2 animate-bounce h-10 w-10 text-white"
            fill="current" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
        </svg>
    </section>
    <section>
        <section class="pt-10 text-white max-w-[1150px] mx-auto text-center">
            <h2 class="text-[40px]" id="projetos">
                Projetos
            </h2>
            <div class="flex flex-wrap pt-4 space-x-[5px] space-y-[5px]">
                @foreach ($projects as $project)
                    <x-cards.project :project="$project"/>
                @endforeach
            </div>
        </section>
    </section>
    <section>
        <section class="pt-16 text-white max-w-[1150px] mx-auto">
            <header class="text-center flex flex-col items-center">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10" fill="none" viewBox="0 0 24 24"
                    stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
                </svg>
                <h2 class="text-[40px]" id="contatos">
                    Contatos
                </h2>
            </header>
            <div class="flex flex-col items-center justify-center pt-10 pb-20 space-y-5">
                <a href="https://api.whatsapp.com/send?phone=5524988671720" target="_blank"
                    class="flex items-center hover:scale-105 transition">
                    <div class="icons-contact">
                        <svg xmlns="http://www.w3.org/2000/svg" class="text-gray-900 h-[55%] w-[55%]"
                            viewBox="0 0 24 24">
                            <path
                                d="M.057 24l1.687-6.163c-1.041-1.804-1.588-3.849-1.587-5.946.003-6.556 5.338-11.891 11.893-11.891 3.181.001 6.167 1.24 8.413 3.488 2.245 2.248 3.481 5.236 3.48 8.414-.003 6.557-5.338 11.892-11.893 11.892-1.99-.001-3.951-.5-5.688-1.448l-6.305 1.654zm6.597-3.807c1.676.995 3.276 1.591 5.392 1.592 5.448 0 9.886-4.434 9.889-9.885.002-5.462-4.415-9.89-9.881-9.892-5.452 0-9.887 4.434-9.889 9.884-.001 2.225.651 3.891 1.746 5.634l-.999 3.648 3.742-.981zm11.387-5.464c-.074-.124-.272-.198-.57-.347-.297-.149-1.758-.868-2.031-.967-.272-.099-.47-.149-.669.149-.198.297-.768.967-.941 1.165-.173.198-.347.223-.644.074-.297-.149-1.255-.462-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.297-.347.446-.521.151-.172.2-.296.3-.495.099-.198.05-.372-.025-.521-.075-.148-.669-1.611-.916-2.206-.242-.579-.487-.501-.669-.51l-.57-.01c-.198 0-.52.074-.792.372s-1.04 1.016-1.04 2.479 1.065 2.876 1.213 3.074c.149.198 2.095 3.2 5.076 4.487.709.306 1.263.489 1.694.626.712.226 1.36.194 1.872.118.571-.085 1.758-.719 2.006-1.413.248-.695.248-1.29.173-1.414z" />
                        </svg>
                    </div>
                    <p class="ml-3 font-light text-[30px]">
                        (24)98867-1720
                    </p>
                </a>
                <section class="hidden flex items-center">
                    <div class="icons-contact">
                        <svg xmlns="http://www.w3.org/2000/svg" class="text-gray-900 h-[60%] w-[60%]" fill="none"
                            viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M16 12a4 4 0 10-8 0 4 4 0 008 0zm0 0v1.5a2.5 2.5 0 005 0V12a9 9 0 10-9 9m4.5-1.206a8.959 8.959 0 01-4.5 1.207" />
                        </svg>
                    </div>
                </section>
            </div>
        </section>
    </section>
</x-guest-layout>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ url(mix('css/app.css')) }}">
        <link rel="stylesheet" href="{{ url(mix('css/text-editor.css')) }}">
        <!-- Scripts -->
        <script src="{{ url(mix('js/app.js')) }}" defer></script>

        <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>

        @stack('styles')
        @stack('scripts')
        @livewireStyles
    </head>
    <body class="font-sans antialiased" x-data="{modal: false}">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
        <x-notification.toaster />
        @livewireScripts
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rondineier de Paula</title>
    <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
    <link rel="stylesheet" href="{{url(mix('css/app.css'))}}">
    <link rel="stylesheet" href="{{url(mix('css/text-editor.css'))}}">
    <!-- Scripts -->
    <script src="{{ url(mix('js/app.js')) }}" defer></script>
    <meta name="csrf-token" content="{{ csrf_token() }}">
</head>

<body x-data="{scroll: 0}" x-on:scroll.window="scroll = window.pageYOffset" class="min-h-screen bg-no-repeat bg-cover bg-center bg-fixed" style="background-image: url('{{asset('storage/images/bg.jpg')}}')">
    <header x-data="{menu: false}" class="w-full">
        <div
        x-bind:class="scroll > 100 ? 'bg-gray-900 md:bg-opacity-70' : ''"
        class="flex flex-col md:flex-row text-white items-center justify-center py-5 w-full fixed top-0 left-0 z-40">
            <button class="md:hidden" @click="menu = !menu">
                <svg x-show="menu === false" xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 transition-opacity" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                </svg>
                <svg x-show="menu === true" xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 transition-opacity" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                </svg>
            </button>
            <x-menu.group-menu>
                <x-menu.item-menu :href="route('home')" text="Início"/>
                <x-menu.item-menu href="#projetos" text="Projetos"/>
                <x-menu.item-menu href="#contatos" text="Contato"/>
            </x-menu.group-menu>
        </div>
    </header>
    <main class="min-h-screen">
        {{$slot}}
    </main>
    <footer>
    </footer>
</body>

</html>

resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="flex-shrink-0 flex items-center">
                    <a href="">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('admin.dashboard')" :active="request()->routeIs('admin.dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                    <x-nav-link :href="route('admin.posts')" :active="request()->routeIs('admin.posts')">
                        {{ __('Posts') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log Out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('admin.dashboard')" :active="request()->routeIs('admin.dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="px-4">
                <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>

resources/views/livewire/admin/dashboard.blade.php
<div>
    {{-- Knowing others is intelligence; knowing yourself is true wisdom. --}}
</div>

resources/views/livewire/admin/post-crud.blade.php
<div>
    <x-modal.modal title="Post" nameModal="new">
        <x-form.group id="title" label="Título" type="text"/>
        <x-form.group id="coverInput" label="Imagem Capa" type="file" icon="image" placeholder="Selecione uma imagem de capa"/>
        <x-form.group id="description" label="Descrição" type="text-editor"/>
        <x-form.group id="type" label="Tipo" type="select">
            <option value="">Selecione um tipo</option>
            <option value="project">Projeto</option>
            <option value="post">Post</option>
        </x-form.group>
        <x-buttons.md class="bg-green-500 m-4 text-white" wire:click="store()">
            Salvar
        </x-buttons.md>
    </x-modal.modal>
</div>

resources/views/livewire/admin/post-index.blade.php
<div class="w-full p-5">
    <x-admin.searchbox.searchbox
    :new="[
        'title'=>'Novo Post'
    ]"/>
    <div class="w-full">
        @foreach ($posts as $post)
            <div class="p-2 flex justify-between bg-white mt-2 border border-gray-300 rounded-lg items-center">
                <h2 class="text-md">{{$post->title}}</h2>
                <div class="flex">
                    <x-buttons.btn class="bg-yellow-400 text-black mr-2" x-on:click="$wire.emit('edit',{{$post->id}})">
                        Editar
                    </x-buttons.btn>
                    <x-buttons.btn class="bg-red-500" x-on:click="confirm('Tem certeza que deseja excluir?') ? $wire.emit('destroy', {{$post->id}}) : ''">
                        Deletar
                    </x-buttons.btn>
                </div>
            </div>
        @endforeach
    </div>
</div>
@livewire('admin.post-crud')

resources/views/project.blade.php
<x-guest-layout>
    <div class="text-white pt-[87px]">
        <section class="bg-gray-500 bg-opacity-30 py-7">
            <div class="mx-auto w-full flex flex-wrap max-w-[1100px]">
                <div class="w-1/2">
                    <img src="{{$post->photoCover()}}" alt="{{$post->title}}" class="rounded-lg shadow-xl object-cover object-center w-full">
                    <section class="w-full text-center">
                        <a href="#" class="
                            inline-block
                            border
                            border-blue-700
                            rounded-sm py-2
                            px-4
                            mt-5
                            shadow-xl
                            transition
                            bg-blue-600
                            hover:bg-blue-500
                            hover:scale-105
                        ">
                            Ver outros projetos
                        </a>
                    </section>
                </div>
                <div class="w-1/2 pl-5 mt-0">
                    <h1 class="text-[35px] font-light">{{$post->title}}</h1>
                    <article class="mt-5">
                        {!!$post->description!!}
                    </article>
                </div>
            </div>
        </section>
    </div>
</x-guest-layout>